deploy_develop2:
  tags:
    - develop2
  before_script:
    - whoami > /var/tmp/ygk-dev1.txt
    - eval $(ssh-agent -s)
    - ssh-add /home/ec2-user/.ssh/id_rsa
    - cd /var/www/html/develop2
  environment:
    name: develop2
  when: manual
  script:
    - git checkout .
    - git pull origin
  only:
    - develop2
