deploy_staging2:
  tags:
    - staging2
  before_script:
    - whoami > /var/tmp/ygk-staging2.txt
    - eval $(ssh-agent -s)
    - ssh-add /home/ec2-user/.ssh/id_rsa
    - cd /var/www/html/staging2
  environment:
    name: staging2
  when: manual
  script:
    - git checkout .
    - git pull origin
  only:
    - staging2
