deploy_develop:
  tags:
    - develop
  before_script:
    - whoami > /var/tmp/ygk-dev.txt
    - eval $(ssh-agent -s)
    - ssh-add /home/ec2-user/.ssh/id_rsa
    - cd /var/www/html/staging_dev
  environment:
    name: develop
  when: manual
  script:
    - git checkout .
    - git pull origin
  only:
    - develop
